updated link to github from google code, few more improvements to gen_gui

diff --git a/gen_gui b/gen_gui
--- a/gen_gui
+++ b/gen_gui
@@ -1,7 +1,7 @@
 #!/bin/bash -u
 
 # omega API engine
-# http://code.google.com/p/theomega/
+# https://github.com/jfillmore/Omega-API-Engine
 # 
 # Copyright 2011, Jonathon Fillmore
 # Licensed under the MIT license. See LICENSE file.
@@ -30,9 +30,9 @@ function usage {
 	   -p, --perms PERMS   OS perms for output files. Default: $os_perms
 	   -o, --opt OPTIMIZE  Optimization level. Default: $optimization
 	   --js-dir DIR        Directory to output JS file to.
-	                         Default: $(BASE_DIR)
+	                         Default: $(pwd -P)
 	   --css-dir DIR       Directory to output JS file to.
-	                         Default: $(BASE_DIR)
+	                         Default: $(pwd -P)
 	   --compiler PATH     Path to google code compiler. Default: $compiler
 	   -h, --help          This information.
 	
@@ -53,8 +53,8 @@ function fail {
 # variable to customize build by -- TODO: build into param system
 #======================================================
 declare name=$(basename $(pwd -P))
-declare js_dir=''
-declare css_dir=''
+declare js_dir='./'
+declare css_dir='./'
 declare js_files=()
 declare css_files=()
 declare compiler=~/scripts/compiler.jar
@@ -136,9 +136,8 @@ while [ $# -gt 0 ]; do
 done
 
 # sanity check
-cd "$BASE_DIR" || fail "Failed to change directory to '$BASE_DIR'."
 [[ -d "$css_dir" && -d "$js_dir" ]] \
-	|| fail "Can't find $css_dir or $js_dir."
+	|| fail "Can't find CSS directory $css_dir or JavaScript directory $js_dir."
 java -version &>/dev/null \
 	|| fail "Missing or broken java JRE."
 jscc="java -jar $compiler"
@@ -146,68 +145,74 @@ cc_code='var a=3;'
 cc_test=$(echo "$cc_code" | $jscc)
 [ "$cc_code" == "$cc_test" ] \
 	|| fail "Google code compiler not found or working properly."
+[[ ${#js_files[*]} -eq 0 && ${#css_files[*]} -eq 0 ]] \
+	&& fail "You must supply at least one JavaScript or CSS file."
 
 #
 # JavaScript
 # ----------
-cat ${js_files[*]} > "$js_dir/.$name.dev.js.$$" \
-	|| fail "Failed to concatinate javascript files together."
-#TODO: run through jslint first and abort on errors, customizing as needed?
-errors=$($jscc --compilation_level $optimization \
-	--js "$js_dir/.$name.dev.js.$$" \
-	2>&1 > "$js_dir/$name.js.compiling")
-[ $? -eq 0 ] || {
-	# lets get a bit more information about the errors, as all the JS is mixed
-	# e.g. "public/js/.enduser_cp.dev.js.2337:8529: ERROR - blah, blah, blah."
-	# try to get the file name to show a bit more detail
-	echo "$errors" | awk -F: '/: ERROR / {print $2, $1, $3}' | while read line file errmsg; do
-		pre_line=$((line-5))
-		post_line=$((line+5))
-		echo "$errmsg"
-		echo "$pre_line v------------------------------------------v"
-		sed "$pre_line,$post_line"'!d' "$file" | sed 's/\t/  /'
-		echo "$post_line ^------------------------------------------^"
-		echo
-	done
-	fail "Javascript compilation failures, compilation aborted."
+[ ${#js_files[*]} -gt 0 ] && {
+	cat ${js_files[*]} > "$js_dir/.$name.dev.js.$$" \
+		|| fail "Failed to concatinate javascript files together."
+	#TODO: run through jslint first and abort on errors, customizing as needed?
+	errors=$($jscc --compilation_level $optimization \
+		--js "$js_dir/.$name.dev.js.$$" \
+		2>&1 > "$js_dir/$name.js.compiling")
+	[ $? -eq 0 ] || {
+		# lets get a bit more information about the errors, as all the JS is mixed
+		# e.g. "public/js/.enduser_cp.dev.js.2337:8529: ERROR - blah, blah, blah."
+		# try to get the file name to show a bit more detail
+		echo "$errors" | awk -F: '/: ERROR / {print $2, $1, $3}' | while read line file errmsg; do
+			pre_line=$((line-5))
+			post_line=$((line+5))
+			echo "$errmsg"
+			echo "$pre_line v------------------------------------------v"
+			sed "$pre_line,$post_line"'!d' "$file" | sed 's/\t/  /'
+			echo "$post_line ^------------------------------------------^"
+			echo
+		done
+		fail "Javascript compilation failures, compilation aborted."
+	}
+	[ $WHOAMI == 'root' ] && {
+		chown $os_user:$os_group "$js_dir/$name.js.compiling" \
+			|| fail "Failed to chown '$js_dir/$name.js.compiling' to $os_user:$os_group"
+		chown $os_user:$os_group "$js_dir/.$name.dev.js.$$" \
+			|| fail "Failed to chown '$js_dir/.$name.dev.js.$$' to $os_user:$os_group"
+	}
+	chmod $os_perms "$js_dir/$name.js.compiling" \
+		|| fail "Failed to chmod '$js_dir/$name.js.compiling' to $os_perms"
+	chmod $os_perms "$js_dir/.$name.dev.js.$$" \
+		|| fail "Failed to chmod $js_dir/.$name.dev.js.$$ to $os_perms"
+	# update build target
+	mv -f "$js_dir/$name.js.compiling" "$js_dir/$name.js" \
+		|| fail "Failed to update '$js_dir/$name.js' with compiled javascript."
+	 # dev build for debugging production
+	mv -f "$js_dir/.$name.dev.js.$$" "$js_dir/$name.dev.js" \
+		|| fail "Failed to update '$js_dir/$name.dev.js' for development build"
 }
-[ $WHOAMI == 'root' ] && {
-	chown $os_user:$os_group "$js_dir/$name.js.compiling" \
-		|| fail "Failed to chown '$js_dir/$name.js.compiling' to $os_user:$os_group"
-	chown $os_user:$os_group "$js_dir/.$name.dev.js.$$" \
-		|| fail "Failed to chown '$js_dir/.$name.dev.js.$$' to $os_user:$os_group"
-}
-chmod $os_perms "$js_dir/$name.js.compiling" \
-	|| fail "Failed to chmod '$js_dir/$name.js.compiling' to $os_perms"
-chmod $os_perms "$js_dir/.$name.dev.js.$$" \
-	|| fail "Failed to chmod $js_dir/.$name.dev.js.$$ to $os_perms"
-# update build target
-mv -f "$js_dir/$name.js.compiling" "$js_dir/$name.js" \
-	|| fail "Failed to update '$js_dir/$name.js' with compiled javascript."
- # dev build for debugging production
-mv -f "$js_dir/.$name.dev.js.$$" "$js_dir/$name.dev.js" \
-	|| fail "Failed to update '$js_dir/$name.dev.js' for development build"
 
 #
 # CSS
 # ---
-cat ${css_files[*]} > "$css_dir/.$name.css.$$" \
-	|| fail "Failed to concatinate CSS files together."
-# TODO: get some CSS validator/minifier?
-# set perms if root
-[ $WHOAMI == 'root' ] && {
-	chown $os_user:$os_group "$css_dir/.$name.css.$$" \
-		|| fail "Failed to chown $css_dir/.$name.css.$$ to $os_user:$os_group"
-}
-chmod $os_perms "$css_dir/.$name.css.$$" \
-	|| fail "Failed to chmod $css_dir/.$name.css.$$ to $os_perms"
-# update build target
-mv -f "$css_dir/.$name.css.$$" "$css_dir/$name.css" \
-	|| fail "Failed to update $css_dir/$name.css with compiled CSS."
+[ ${#css_files[*]} -gt 0 ] && {
+	cat ${css_files[*]} > "$css_dir/.$name.css.$$" \
+		|| fail "Failed to concatinate CSS files together."
+	# TODO: get some CSS validator/minifier?
+	# set perms if root
+	[ $WHOAMI == 'root' ] && {
+		chown $os_user:$os_group "$css_dir/.$name.css.$$" \
+			|| fail "Failed to chown $css_dir/.$name.css.$$ to $os_user:$os_group"
+	}
+	chmod $os_perms "$css_dir/.$name.css.$$" \
+		|| fail "Failed to chmod $css_dir/.$name.css.$$ to $os_perms"
+	# update build target
+	mv -f "$css_dir/.$name.css.$$" "$css_dir/$name.css" \
+		|| fail "Failed to update $css_dir/$name.css with compiled CSS."
 
-# check for 4096+ styles and QQ-- I believe IE shits itself when this happens
-# TODO: find a better way to check this... but it *should* be safe enough of a check for now :)
-[[ $(grep -c '}' $css_dir/$name.css) -ge 4096 ]] \
-	&& fail "BUILD SUCCESSFUL; BUT CSS HAS GONE OVER 4096 LINES. INTERNET EXPLODER MIGHT SHIT ITSELF."
+	# check for 4096+ styles and QQ-- I believe IE shits itself when this happens
+	# TODO: find a better way to check this... but it *should* be safe enough of a check for now :)
+	[[ $(grep -c '}' $css_dir/$name.css) -ge 4096 ]] \
+		&& fail "BUILD SUCCESSFUL; BUT CSS HAS GONE OVER 4096 LINES. INTERNET EXPLODER MIGHT SHIT ITSELF."
+}
 
 exit 0
