fixed intentional bug in om.bf. created to test gen_gui; updated gen_gui w/ bug fixes

diff --git a/gen_gui b/gen_gui
--- a/gen_gui
+++ b/gen_gui
@@ -89,11 +89,15 @@ while [ $# -gt 0 ]; do
 		-u|--user)
 			[ $# -gt 0 ] || fail "Missing argument to --user."
 			os_user="$1"
+			[[ "$WHOAMI" == 'root' && "$WHOAMI" != "$os_user" ]] || \
+				fail "Unable to create output files as '$os_user' without being root or that user."
 			shift
 			;;
 		-g|--group)
 			[ $# -gt 0 ] || fail "Missing argument to --group."
 			os_group="$1"
+			[ "$WHOAMI" == 'root' ] || \
+				fail "Unable to create output files as '$os_user' without being root."
 			shift
 			;;
 		-p|--perms)
@@ -133,22 +137,27 @@ done
 
 # sanity check
 cd "$BASE_DIR" || fail "Failed to change directory to '$BASE_DIR'."
-[[ -d "$css_dir" && "$js_dir" ]] || fail "huh? where am I? can't find $css_dir or $js_dir."
-java -version &>/dev/null || fail "Missing or broken java JRE."
+[[ -d "$css_dir" && -d "$js_dir" ]] \
+	|| fail "Can't find $css_dir or $js_dir."
+java -version &>/dev/null \
+	|| fail "Missing or broken java JRE."
 jscc="java -jar $compiler"
 cc_code='var a=3;'
 cc_test=$(echo "$cc_code" | $jscc)
-[ "$cc_code" == "$cc_test" ] || fail "compiler not found or working properly"
+[ "$cc_code" == "$cc_test" ] \
+	|| fail "Google code compiler not found or working properly."
 
 #
 # JavaScript
 # ----------
-cat ${js_files[*]} > "$js_dir/.$name.dev.js.$$" || fail "Failed to concatinate javascript files together."
+cat ${js_files[*]} > "$js_dir/.$name.dev.js.$$" \
+	|| fail "Failed to concatinate javascript files together."
 #TODO: run through jslint first and abort on errors, customizing as needed?
 errors=$($jscc --compilation_level $optimization \
 	--js "$js_dir/.$name.dev.js.$$" \
 	2>&1 > "$js_dir/$name.js.compiling")
 [ $? -eq 0 ] || {
+	# lets get a bit more information about the errors, as all the JS is mixed
 	# e.g. "public/js/.enduser_cp.dev.js.2337:8529: ERROR - blah, blah, blah."
 	# try to get the file name to show a bit more detail
 	echo "$errors" | awk -F: '/: ERROR / {print $2, $1, $3}' | while read line file errmsg; do
@@ -162,33 +171,43 @@ errors=$($jscc --compilation_level $optimization \
 	done
 	fail "Javascript compilation failures, compilation aborted."
 }
-# set perms if root
 [ $WHOAMI == 'root' ] && {
-	chown $os_user:$os_group "$js_dir/$name.js.compiling" || fail "Failed to chown '$js_dir/$name.js.compiling' to $os_user:$os_group"
-	chmod $os_perms "$js_dir/$name.js.compiling" || fail "Failed to chmod '$js_dir/$name.js.compiling' to $os_perms"
-	chown $os_user:$os_group "$js_dir/.$name.dev.js.$$" || fail "Failed to chown '$js_dir/.$name.dev.js.$$' to $os_user:$os_group"
-	chmod $os_perms "$js_dir/.$name.dev.js.$$" || fail "Failed to chmod $js_dir/.$name.dev.js.$$ to $os_perms"
+	chown $os_user:$os_group "$js_dir/$name.js.compiling" \
+		|| fail "Failed to chown '$js_dir/$name.js.compiling' to $os_user:$os_group"
+	chown $os_user:$os_group "$js_dir/.$name.dev.js.$$" \
+		|| fail "Failed to chown '$js_dir/.$name.dev.js.$$' to $os_user:$os_group"
 }
+chmod $os_perms "$js_dir/$name.js.compiling" \
+	|| fail "Failed to chmod '$js_dir/$name.js.compiling' to $os_perms"
+chmod $os_perms "$js_dir/.$name.dev.js.$$" \
+	|| fail "Failed to chmod $js_dir/.$name.dev.js.$$ to $os_perms"
 # update build target
-mv -f "$js_dir/$name.js.compiling" "$js_dir/$name.js" || fail "Failed to update '$js_dir/$name.js' with compiled javascript."
+mv -f "$js_dir/$name.js.compiling" "$js_dir/$name.js" \
+	|| fail "Failed to update '$js_dir/$name.js' with compiled javascript."
  # dev build for debugging production
-mv -f "$js_dir/.$name.dev.js.$$" "$js_dir/$name.dev.js" || fail "Failed to update '$js_dir/$name.dev.js' for development build"
+mv -f "$js_dir/.$name.dev.js.$$" "$js_dir/$name.dev.js" \
+	|| fail "Failed to update '$js_dir/$name.dev.js' for development build"
 
 #
 # CSS
 # ---
-cat ${css_files[*]} > "$css_dir/.$name.css.$$" || fail "Failed to concatinate CSS files together."
+cat ${css_files[*]} > "$css_dir/.$name.css.$$" \
+	|| fail "Failed to concatinate CSS files together."
 # TODO: get some CSS validator/minifier?
 # set perms if root
 [ $WHOAMI == 'root' ] && {
-	chown $os_user:$os_group "$css_dir/.$name.css.$$" || fail "Failed to chown $css_dir/.$name.css.$$ to $os_user:$os_group"
-	chmod $os_perms "$css_dir/.$name.css.$$" || fail "Failed to chmod $css_dir/.$name.css.$$ to $os_perms"
+	chown $os_user:$os_group "$css_dir/.$name.css.$$" \
+		|| fail "Failed to chown $css_dir/.$name.css.$$ to $os_user:$os_group"
 }
+chmod $os_perms "$css_dir/.$name.css.$$" \
+	|| fail "Failed to chmod $css_dir/.$name.css.$$ to $os_perms"
 # update build target
-mv -f "$css_dir/.$name.css.$$" "$css_dir/$name.css" || fail "Failed to update $css_dir/$name.css with compiled CSS."
+mv -f "$css_dir/.$name.css.$$" "$css_dir/$name.css" \
+	|| fail "Failed to update $css_dir/$name.css with compiled CSS."
 
 # check for 4096+ styles and QQ-- I believe IE shits itself when this happens
 # TODO: find a better way to check this... but it *should* be safe enough of a check for now :)
-[[ $(grep -c '}' $css_dir/$name.css) -ge 4096 ]] && fail "BUILD SUCCESSFUL; BUT CSS HAS GONE OVER 4096 LINES. INTERNET EXPLODER MIGHT SHIT ITSELF."
+[[ $(grep -c '}' $css_dir/$name.css) -ge 4096 ]] \
+	&& fail "BUILD SUCCESSFUL; BUT CSS HAS GONE OVER 4096 LINES. INTERNET EXPLODER MIGHT SHIT ITSELF."
 
 exit 0
